#!/usr/bin/env bash
# Test for file 100-average_weighted_score.sql

echo "CREATE DATABASE IF NOT EXISTS hbtn_advanced;" | mysql -uroot
#----------------
cat '100-init.sql' | mysql -uroot hbtn_advanced
cat '../100-average_weighted_score.sql' | mysql -uroot hbtn_advanced
cat '100-main.sql' | mysql -uroot hbtn_advanced
