#!/usr/bin/env bash
# Test for file 4-store.sql

echo "CREATE DATABASE IF NOT EXISTS hbtn_advanced;" | mysql -uroot
#----------------
cat '4-init.sql' | mysql -uroot hbtn_advanced
cat '../4-store.sql' | mysql -uroot hbtn_advanced
cat '4-main.sql' | mysql -uroot hbtn_advanced
