#!/usr/bin/env bash
# Test for file 5-valid_email.sql

echo "CREATE DATABASE IF NOT EXISTS hbtn_advanced;" | mysql -uroot
#----------------
cat '5-init.sql' | mysql -uroot hbtn_advanced
cat '../5-valid_email.sql' | mysql -uroot hbtn_advanced
cat '5-main.sql' | mysql -uroot hbtn_advanced
