#!/usr/bin/env bash
# Test for file 7-average_score.sql

echo "CREATE DATABASE IF NOT EXISTS hbtn_advanced;" | mysql -uroot
#----------------
cat '7-init.sql' | mysql -uroot hbtn_advanced
cat '../7-average_score.sql' | mysql -uroot hbtn_advanced
cat '7-main.sql' | mysql -uroot hbtn_advanced
